"""
Utility functions for rec_sys
"""

import time
import random


def generate_request_id(worker_id: int = 1) -> int:
    """
    Generate Snowflake-like 64-bit request ID

    Structure:
    - 42 bits: timestamp in milliseconds (supports ~69 years)
    - 10 bits: worker ID (supports 1024 workers)
    - 12 bits: sequence number (4096 requests/ms per worker)

    Args:
        worker_id: Worker/instance identifier (1-1024)

    Returns:
        Unique 64-bit integer request ID

    Examples:
        >>> req_id = generate_request_id()
        >>> req_id > 0
        True
        >>> isinstance(req_id, int)
        True
    """
    # Get current timestamp in milliseconds
    timestamp_ms = int(time.time() * 1000)

    # Ensure worker_id is within valid range (10 bits = 0-1023)
    worker_id = worker_id & 0x3FF

    # Random sequence number (12 bits = 0-4095)
    # In production, use an incrementing counter per worker
    sequence = random.randint(0, 4095)

    # Combine: [42 bits timestamp][10 bits worker][12 bits sequence]
    request_id = (timestamp_ms << 22) | (worker_id << 12) | sequence

    return request_id


def extract_timestamp_from_request_id(request_id: int) -> int:
    """
    Extract timestamp (milliseconds) from a request ID

    Args:
        request_id: Request ID generated by generate_request_id()

    Returns:
        Unix timestamp in milliseconds

    Examples:
        >>> req_id = generate_request_id()
        >>> ts = extract_timestamp_from_request_id(req_id)
        >>> abs(ts - int(time.time() * 1000)) < 1000  # Within 1 second
        True
    """
    return request_id >> 22
